In [85]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
glassdata = pd.read_csv('glass.csv') 
print(glassdata)
print(np.unique(glassdata['Type']))
# Notice that in the description, it has 1-7 types, but the dataset does not have Type 4

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]
[1 2 3 5 6 7]


In [86]:
glassdata.describe()

RI          Na          Mg          Al          Si           K  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056   
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192   
min      1.511150   10.730000    0.000000    0.290000   69.810000    0.000000   
25%      1.516522   12.907500    2.115000    1.190000   72.280000    0.122500   
50%      1.517680   13.300000    3.480000    1.360000   72.790000    0.555000   
75%      1.519157   13.825000    3.600000    1.630000   73.087500    0.610000   
max      1.533930   17.380000    4.490000    3.500000   75.410000    6.210000   

               Ca          Ba          Fe        Type  
count  214.000000  214.000000  214.000000  214.000000  
mean     8.956963    0.175047    0.057009    2.780374  
std      1.423153    0.497219    0.097439    2.103739  
min      5.430000    0.000000    0.000000    1.000000  
25%      8.240000    0.000000    0.000000    1.000000  
50%      8.600000    0.000000    0.000000    2.000000  
75%      9.172500    0.000000    0.100000    3.000000  
max     16.190000    3.150000    0.510000    7.000000

In [87]:
print ((glassdata['Ba']==0).sum()/len(glassdata))
print ((glassdata['Fe']==0).sum()/len(glassdata))

0.822429906542056
0.6728971962616822


In [88]:
glassdata.drop('Ba',axis=1,inplace=True)
glassdata.drop('Fe',axis=1,inplace=True)

In [89]:
print(glassdata)

          RI     Na    Mg    Al     Si     K    Ca  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07     1
..       ...    ...   ...   ...    ...   ...   ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62     7

[214 rows x 8 columns]


In [90]:
Y=glassdata.iloc[:,-1:]
X=glassdata.iloc[:,:-1]
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3)

In [91]:
#pd.plotting.scatter_matrix(X_train, alpha=0.8, figsize=(10, 10))

In [92]:
from sklearn.svm import SVC
svm = SVC(kernel='rbf',C=0.8)
#Regularization parameter C
#kernel{‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’} or callable, default=’rbf’

svm.fit(X_train, y_train.values.flatten())
y_pred=svm.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))


from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))


from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


0.38461538461538464
[[ 0 24  0  0  0  0]
 [ 0 25  0  0  0  0]
 [ 0  5  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  3  0  0  0  0]
 [ 0  6  0  0  0  0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        24
           2       0.38      1.00      0.56        25
           3       0.00      0.00      0.00         5
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3
           7       0.00      0.00      0.00         6

    accuracy                           0.38        65
   macro avg       0.06      0.17      0.09        65
weighted avg       0.15      0.38      0.21        65



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Precision = TruePositives / (TruePositives + FalsePositives)  Precision: Appropriate when minimizing false positives is the focus.

Recall = TruePositives / (TruePositives + FalseNegatives)
Recall: Appropriate when minimizing false negatives is the focus.

F-Measure = (2 * Precision * Recall) / (Precision + Recall)


In [93]:
#prediction
pre=pd.DataFrame([[1.51711,  14.23,  0.00,  2.08,  73.36,  0.00,  8.62]])
predict_out=svm.predict(pre)
print(predict_out)

[2]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"


https://www.oreilly.com/library/view/python-end-to-end-data/9781788394697/ch18s03.html

*KNN* K-Nearest Neighbour algorithum

In [94]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [95]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, [1, 2, 3]].values
y = dataset.iloc[:, -1].values
print(dataset)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [96]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])
#Since our dataset containing character variables we have to encode it using LabelEncoder
print(X)

[[1 19 19000]
 [1 35 20000]
 [0 26 43000]
 ...
 [0 50 20000]
 [1 36 33000]
 [0 49 36000]]


In [97]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [98]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [99]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
#p = 1, this is equivalent to using manhattan_distance (l1), and euclidean_distance (l2) for p = 2
#metric = 'minkowski'- Distance metric is used
classifier.fit(X_train, y_train)


KNeighborsClassifier()

In [100]:
y_pred = classifier.predict(X_test)

In [101]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)
print(cm, ac)

[[55  3]
 [ 1 21]] 0.95


In [115]:
pred = classifier.predict([[0,50,20000]])
print(pred)

[1]


[1]


In [31]:
#RandomForestClassifier

In [9]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(max_depth=5, random_state=0)

model.fit(X_train, y_train.values.flatten())
y_pred=model.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))


from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))


from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

0.6923076923076923
[[17  4  0  0  0  0]
 [ 4 17  1  0  2  0]
 [ 3  2  1  0  0  0]
 [ 0  2  0  2  0  0]
 [ 0  0  0  0  1  0]
 [ 1  1  0  0  0  7]]
              precision    recall  f1-score   support

           1       0.68      0.81      0.74        21
           2       0.65      0.71      0.68        24
           3       0.50      0.17      0.25         6
           5       1.00      0.50      0.67         4
           6       0.33      1.00      0.50         1
           7       1.00      0.78      0.88         9

    accuracy                           0.69        65
   macro avg       0.69      0.66      0.62        65
weighted avg       0.71      0.69      0.68        65

